environment:
    global:
        PROJECT_NAME: zemeroth
    matrix:
        - TARGET: i686-pc-windows-gnu
          CHANNEL: stable
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable
        - TARGET: x86_64-pc-windows-gnu
          CHANNEL: stable
        - TARGET: x86_64-pc-windows-gnu
          CHANNEL: beta
        - TARGET: x86_64-pc-windows-gnu
          CHANNEL: nightly

matrix:
    allow_failures:
        - CHANNEL: nightly

install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - set PATH=C:\msys64\mingw32\bin;%PATH%
    - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

build: false

test_script:
    - cmd: 'cargo build && cargo test && cargo build --release'

# cache:
#     - target
#     - C:\Users\appveyor\.cargo\registry

before_deploy:
    - mkdir staging
    - mkdir staging\assets
    - copy target\release\zemeroth.exe staging
    - cd staging
    - git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
    - 7z a ../%PROJECT_NAME%-%TARGET%.zip *
    - appveyor PushArtifact ../%PROJECT_NAME%-%TARGET%.zip

deploy:
    provider: GitHub
    artifact: /.*\.zip/
    auth_token:
        secure: ENk8Tp+3wU90QF5utTGj5QM3bYyXHRtWm+mMgH+SotiCbIRc6mf0DsoKQgA1F/64
    on:
        CHANNEL: stable
        appveyor_repo_tag: true
        branch:
            - master
