#!/bin/sh

set -e

PROJ="$(grep -Po 'name = "\K[^\"]*' Cargo.toml)"
echo $PROJ

cargo apk

adb install -r ./target/android-artifacts/build/bin/$PROJ-debug.apk

adb logcat -c
adb shell am start -n rust.$PROJ/rust.$PROJ.MainActivity
mkdir -p logs
adb logcat -v time | tee logs/android_log_$(date +%F_%R) | grep 'Rust'
